name: oneofus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.59+59

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  intl: ^0.20.1
  convert: ^3.1.1
  cryptography: ^2.7.0
  jwk: ^0.2.3
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^6.0.0
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  fake_cloud_firestore: ^3.0.2
  url_launcher: ^6.3.0
  flutter_linkify: ^6.0.0
  share_plus: ^11.0.0
  loader_overlay: ^5.0.0
  package_info_plus: ^8.1.1
  http: ^1.2.2
  cloud_functions: ^5.3.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path_android: assets/images/oneofus.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/

